INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.01', 'KAB. ACEH SELATAN', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.02', 'KAB. ACEH TENGGARA', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.03', 'KAB. ACEH TIMUR', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.04', 'KAB. ACEH TENGAH', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.05', 'KAB. ACEH BARAT', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.06', 'KAB. ACEH BESAR', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.07', 'KAB. PIDIE', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.08', 'KAB. ACEH UTARA', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.09', 'KAB. SIMEULUE', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.1', 'KAB. ACEH SINGKIL', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.11', 'KAB. BIREUEN', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.12', 'KAB. ACEH BARAT DAYA', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.13', 'KAB. GAYO LUES', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.14', 'KAB. ACEH JAYA', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.15', 'KAB. NAGAN RAYA', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.16', 'KAB. ACEH TAMIANG', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.17', 'KAB. BENER MERIAH', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.18', 'KAB. PIDIE JAYA', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.71', 'KOTA BANDA ACEH', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.72', 'KOTA SABANG', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.73', 'KOTA LHOKSEUMAWE', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.74', 'KOTA LANGSA', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('11.75', 'KOTA SUBULUSSALAM', NULL, NULL, NULL, '11');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.01', 'KAB. TAPANULI TENGAH', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.02', 'KAB. TAPANULI UTARA', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.03', 'KAB. TAPANULI SELATAN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.04', 'KAB. NIAS', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.05', 'KAB. LANGKAT', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.06', 'KAB. KARO', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.07', 'KAB. DELI SERDANG', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.08', 'KAB. SIMALUNGUN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.09', 'KAB. ASAHAN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.1', 'KAB. LABUHANBATU', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.11', 'KAB. DAIRI', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.12', 'KAB. TOBA', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.13', 'KAB. MANDAILING NATAL', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.14', 'KAB. NIAS SELATAN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.15', 'KAB. PAKPAK BHARAT', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.16', 'KAB. HUMBANG HASUNDUTAN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.17', 'KAB. SAMOSIR', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.18', 'KAB. SERDANG BEDAGAI', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.19', 'KAB. BATU BARA', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.2', 'KAB. PADANG LAWAS UTARA', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.21', 'KAB. PADANG LAWAS', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.22', 'KAB. LABUHANBATU SELATAN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.23', 'KAB. LABUHANBATU UTARA', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.24', 'KAB. NIAS UTARA', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.25', 'KAB. NIAS BARAT', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.71', 'KOTA MEDAN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.72', 'KOTA PEMATANGSIANTAR', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.73', 'KOTA SIBOLGA', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.74', 'KOTA TANJUNG BALAI', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.75', 'KOTA BINJAI', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.76', 'KOTA TEBING TINGGI', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.77', 'KOTA PADANGSIDIMPUAN', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('12.78', 'KOTA GUNUNGSITOLI', NULL, NULL, NULL, '12');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.01', 'KAB. PESISIR SELATAN', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.02', 'KAB. SOLOK', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.03', 'KAB. SIJUNJUNG', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.04', 'KAB. TANAH DATAR', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.05', 'KAB. PADANG PARIAMAN', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.06', 'KAB. AGAM', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.07', 'KAB. LIMA PULUH KOTA', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.08', 'KAB. PASAMAN', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.09', 'KAB. KEPULAUAN MENTAWAI', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.1', 'KAB. DHARMASRAYA', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.11', 'KAB. SOLOK SELATAN', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.12', 'KAB. PASAMAN BARAT', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.71', 'KOTA PADANG', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.72', 'KOTA SOLOK', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.73', 'KOTA SAWAHLUNTO', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.74', 'KOTA PADANG PANJANG', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.75', 'KOTA BUKITTINGGI', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.76', 'KOTA PAYAKUMBUH', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('13.77', 'KOTA PARIAMAN', NULL, NULL, NULL, '13');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.01', 'KAB. KAMPAR', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.02', 'KAB. INDRAGIRI HULU', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.03', 'KAB. BENGKALIS', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.04', 'KAB. INDRAGIRI HILIR', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.05', 'KAB. PELALAWAN', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.06', 'KAB. ROKAN HULU', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.07', 'KAB. ROKAN HILIR', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.08', 'KAB. SIAK', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.09', 'KAB. KUANTAN SINGINGI', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.1', 'KAB. KEPULAUAN MERANTI', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.71', 'KOTA PEKANBARU', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('14.72', 'KOTA DUMAI', NULL, NULL, NULL, '14');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.01', 'KAB. KERINCI', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.02', 'KAB. MERANGIN', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.03', 'KAB. SAROLANGUN', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.04', 'KAB. BATANGHARI', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.05', 'KAB. MUARO JAMBI', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.06', 'KAB. TANJUNG JABUNG BARAT', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.07', 'KAB. TANJUNG JABUNG TIMUR', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.08', 'KAB. BUNGO', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.09', 'KAB. TEBO', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.71', 'KOTA JAMBI', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('15.72', 'KOTA SUNGAI PENUH', NULL, NULL, NULL, '15');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.01', 'KAB. OGAN KOMERING ULU', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.02', 'KAB. OGAN KOMERING ILIR', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.03', 'KAB. MUARA ENIM', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.04', 'KAB. LAHAT', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.05', 'KAB. MUSI RAWAS', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.06', 'KAB. MUSI BANYUASIN', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.07', 'KAB. BANYUASIN', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.08', 'KAB. OGAN KOMERING ULU TIMUR', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.09', 'KAB. OGAN KOMERING ULU SELATAN', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.1', 'KAB. OGAN ILIR', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.11', 'KAB. EMPAT LAWANG', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.12', 'KAB. PENUKAL ABAB LEMATANG ILIR', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.13', 'KAB. MUSI RAWAS UTARA', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.71', 'KOTA PALEMBANG', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.72', 'KOTA PAGAR ALAM', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.73', 'KOTA LUBUK LINGGAU', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('16.74', 'KOTA PRABUMULIH', NULL, NULL, NULL, '16');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.01', 'KAB. BENGKULU SELATAN', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.02', 'KAB. REJANG LEBONG', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.03', 'KAB. BENGKULU UTARA', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.04', 'KAB. KAUR', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.05', 'KAB. SELUMA', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.06', 'KAB. MUKO MUKO', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.07', 'KAB. LEBONG', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.08', 'KAB. KEPAHIANG', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.09', 'KAB. BENGKULU TENGAH', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('17.71', 'KOTA BENGKULU', NULL, NULL, NULL, '17');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.01', 'KAB. LAMPUNG SELATAN', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.02', 'KAB. LAMPUNG TENGAH', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.03', 'KAB. LAMPUNG UTARA', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.04', 'KAB. LAMPUNG BARAT', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.05', 'KAB. TULANG BAWANG', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.06', 'KAB. TANGGAMUS', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.07', 'KAB. LAMPUNG TIMUR', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.08', 'KAB. WAY KANAN', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.09', 'KAB. PESAWARAN', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.1', 'KAB. PRINGSEWU', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.11', 'KAB. MESUJI', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.12', 'KAB. TULANG BAWANG BARAT', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.13', 'KAB. PESISIR BARAT', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.71', 'KOTA BANDAR LAMPUNG', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('18.72', 'KOTA METRO', NULL, NULL, NULL, '18');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('19.01', 'KAB. BANGKA', NULL, NULL, NULL, '19');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('19.02', 'KAB. BELITUNG', NULL, NULL, NULL, '19');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('19.03', 'KAB. BANGKA SELATAN', NULL, NULL, NULL, '19');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('19.04', 'KAB. BANGKA TENGAH', NULL, NULL, NULL, '19');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('19.05', 'KAB. BANGKA BARAT', NULL, NULL, NULL, '19');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('19.06', 'KAB. BELITUNG TIMUR', NULL, NULL, NULL, '19');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('19.71', 'KOTA PANGKAL PINANG', NULL, NULL, NULL, '19');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('21.01', 'KAB. BINTAN', NULL, NULL, NULL, '21');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('21.02', 'KAB. KARIMUN', NULL, NULL, NULL, '21');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('21.03', 'KAB. NATUNA', NULL, NULL, NULL, '21');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('21.04', 'KAB. LINGGA', NULL, NULL, NULL, '21');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('21.05', 'KAB. KEPULAUAN ANAMBAS', NULL, NULL, NULL, '21');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('21.71', 'KOTA BATAM', NULL, NULL, NULL, '21');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('21.72', 'KOTA TANJUNG PINANG', NULL, NULL, NULL, '21');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('31.01', 'KAB. ADM. KEP. SERIBU', NULL, NULL, NULL, '31');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('31.71', 'KOTA ADM. JAKARTA PUSAT', NULL, NULL, NULL, '31');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('31.72', 'KOTA ADM. JAKARTA UTARA', NULL, NULL, NULL, '31');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('31.73', 'KOTA ADM. JAKARTA BARAT', NULL, NULL, NULL, '31');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('31.74', 'KOTA ADM. JAKARTA SELATAN', NULL, NULL, NULL, '31');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('31.75', 'KOTA ADM. JAKARTA TIMUR', NULL, NULL, NULL, '31');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.01', 'KAB. BOGOR', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.02', 'KAB. SUKABUMI', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.03', 'KAB. CIANJUR', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.04', 'KAB. BANDUNG', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.05', 'KAB. GARUT', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.06', 'KAB. TASIKMALAYA', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.07', 'KAB. CIAMIS', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.08', 'KAB. KUNINGAN', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.09', 'KAB. CIREBON', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.1', 'KAB. MAJALENGKA', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.11', 'KAB. SUMEDANG', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.12', 'KAB. INDRAMAYU', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.13', 'KAB. SUBANG', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.14', 'KAB. PURWAKARTA', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.15', 'KAB. KARAWANG', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.16', 'KAB. BEKASI', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.17', 'KAB. BANDUNG BARAT', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.18', 'KAB. PANGANDARAN', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.71', 'KOTA BOGOR', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.72', 'KOTA SUKABUMI', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.73', 'KOTA BANDUNG', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.74', 'KOTA CIREBON', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.75', 'KOTA BEKASI', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.76', 'KOTA DEPOK', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.77', 'KOTA CIMAHI', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.78', 'KOTA TASIKMALAYA', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('32.79', 'KOTA BANJAR', NULL, NULL, NULL, '32');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.01', 'KAB. CILACAP', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.02', 'KAB. BANYUMAS', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.03', 'KAB. PURBALINGGA', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.04', 'KAB. BANJARNEGARA', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.05', 'KAB. KEBUMEN', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.06', 'KAB. PURWOREJO', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.07', 'KAB. WONOSOBO', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.08', 'KAB. MAGELANG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.09', 'KAB. BOYOLALI', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.1', 'KAB. KLATEN', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.11', 'KAB. SUKOHARJO', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.12', 'KAB. WONOGIRI', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.13', 'KAB. KARANGANYAR', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.14', 'KAB. SRAGEN', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.15', 'KAB. GROBOGAN', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.16', 'KAB. BLORA', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.17', 'KAB. REMBANG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.18', 'KAB. PATI', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.19', 'KAB. KUDUS', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.2', 'KAB. JEPARA', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.21', 'KAB. DEMAK', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.22', 'KAB. SEMARANG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.23', 'KAB. TEMANGGUNG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.24', 'KAB. KENDAL', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.25', 'KAB. BATANG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.26', 'KAB. PEKALONGAN', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.27', 'KAB. PEMALANG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.28', 'KAB. TEGAL', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.29', 'KAB. BREBES', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.71', 'KOTA MAGELANG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.72', 'KOTA SURAKARTA', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.73', 'KOTA SALATIGA', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.74', 'KOTA SEMARANG', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.75', 'KOTA PEKALONGAN', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('33.76', 'KOTA TEGAL', NULL, NULL, NULL, '33');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('34.01', 'KAB. KULON PROGO', NULL, NULL, NULL, '34');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('34.02', 'KAB. BANTUL', NULL, NULL, NULL, '34');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('34.03', 'KAB. GUNUNGKIDUL', NULL, NULL, NULL, '34');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('34.04', 'KAB. SLEMAN', NULL, NULL, NULL, '34');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('34.71', 'KOTA YOGYAKARTA', NULL, NULL, NULL, '34');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.01', 'KAB. PACITAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.02', 'KAB. PONOROGO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.03', 'KAB. TRENGGALEK', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.04', 'KAB. TULUNGAGUNG', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.05', 'KAB. BLITAR', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.06', 'KAB. KEDIRI', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.07', 'KAB. MALANG', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.08', 'KAB. LUMAJANG', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.09', 'KAB. JEMBER', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.1', 'KAB. BANYUWANGI', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.11', 'KAB. BONDOWOSO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.12', 'KAB. SITUBONDO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.13', 'KAB. PROBOLINGGO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.14', 'KAB. PASURUAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.15', 'KAB. SIDOARJO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.16', 'KAB. MOJOKERTO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.17', 'KAB. JOMBANG', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.18', 'KAB. NGANJUK', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.19', 'KAB. MADIUN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.2', 'KAB. MAGETAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.21', 'KAB. NGAWI', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.22', 'KAB. BOJONEGORO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.23', 'KAB. TUBAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.24', 'KAB. LAMONGAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.25', 'KAB. GRESIK', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.26', 'KAB. BANGKALAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.27', 'KAB. SAMPANG', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.28', 'KAB. PAMEKASAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.29', 'KAB. SUMENEP', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.71', 'KOTA KEDIRI', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.72', 'KOTA BLITAR', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.73', 'KOTA MALANG', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.74', 'KOTA PROBOLINGGO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.75', 'KOTA PASURUAN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.76', 'KOTA MOJOKERTO', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.77', 'KOTA MADIUN', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.78', 'KOTA SURABAYA', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('35.79', 'KOTA BATU', NULL, NULL, NULL, '35');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.01', 'KAB. PANDEGLANG', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.02', 'KAB. LEBAK', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.03', 'KAB. TANGERANG', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.04', 'KAB. SERANG', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.71', 'KOTA TANGERANG', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.72', 'KOTA CILEGON', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.73', 'KOTA SERANG', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('36.74', 'KOTA TANGERANG SELATAN', NULL, NULL, NULL, '36');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.01', 'KAB. JEMBRANA', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.02', 'KAB. TABANAN', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.03', 'KAB. BADUNG', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.04', 'KAB. GIANYAR', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.05', 'KAB. KLUNGKUNG', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.06', 'KAB. BANGLI', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.07', 'KAB. KARANGASEM', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.08', 'KAB. BULELENG', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('51.71', 'KOTA DENPASAR', NULL, NULL, NULL, '51');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.01', 'KAB. LOMBOK BARAT', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.02', 'KAB. LOMBOK TENGAH', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.03', 'KAB. LOMBOK TIMUR', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.04', 'KAB. SUMBAWA', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.05', 'KAB. DOMPU', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.06', 'KAB. BIMA', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.07', 'KAB. SUMBAWA BARAT', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.08', 'KAB. LOMBOK UTARA', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.71', 'KOTA MATARAM', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('52.72', 'KOTA BIMA', NULL, NULL, NULL, '52');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.01', 'KAB. KUPANG', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.02', 'KAB TIMOR TENGAH SELATAN', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.03', 'KAB. TIMOR TENGAH UTARA', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.04', 'KAB. BELU', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.05', 'KAB. ALOR', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.06', 'KAB. FLORES TIMUR', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.07', 'KAB. SIKKA', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.08', 'KAB. ENDE', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.09', 'KAB. NGADA', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.1', 'KAB. MANGGARAI', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.11', 'KAB. SUMBA TIMUR', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.12', 'KAB. SUMBA BARAT', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.13', 'KAB. LEMBATA', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.14', 'KAB. ROTE NDAO', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.15', 'KAB. MANGGARAI BARAT', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.16', 'KAB. NAGEKEO', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.17', 'KAB. SUMBA TENGAH', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.18', 'KAB. SUMBA BARAT DAYA', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.19', 'KAB. MANGGARAI TIMUR', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.2', 'KAB. SABU RAIJUA', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.21', 'KAB. MALAKA', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('53.71', 'KOTA KUPANG', NULL, NULL, NULL, '53');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.01', 'KAB. SAMBAS', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.02', 'KAB. MEMPAWAH', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.03', 'KAB. SANGGAU', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.04', 'KAB. KETAPANG', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.05', 'KAB. SINTANG', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.06', 'KAB. KAPUAS HULU', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.07', 'KAB. BENGKAYANG', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.08', 'KAB. LANDAK', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.09', 'KAB. SEKADAU', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.1', 'KAB. MELAWI', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.11', 'KAB. KAYONG UTARA', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.12', 'KAB. KUBU RAYA', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.71', 'KOTA PONTIANAK', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('61.72', 'KOTA SINGKAWANG', NULL, NULL, NULL, '61');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.01', 'KAB. KOTAWARINGIN BARAT', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.02', 'KAB. KOTAWARINGIN TIMUR', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.03', 'KAB. KAPUAS', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.04', 'KAB. BARITO SELATAN', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.05', 'KAB. BARITO UTARA', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.06', 'KAB. KATINGAN', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.07', 'KAB. SERUYAN', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.08', 'KAB. SUKAMARA', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.09', 'KAB. LAMANDAU', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.1', 'KAB. GUNUNG MAS', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.11', 'KAB. PULANG PISAU', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.12', 'KAB. MURUNG RAYA', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.13', 'KAB. BARITO TIMUR', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('62.71', 'KOTA PALANGKARAYA', NULL, NULL, NULL, '62');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.01', 'KAB. TANAH LAUT', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.02', 'KAB. KOTABARU', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.03', 'KAB. BANJAR', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.04', 'KAB. BARITO KUALA', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.05', 'KAB. TAPIN', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.06', 'KAB. HULU SUNGAI SELATAN', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.07', 'KAB. HULU SUNGAI TENGAH', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.08', 'KAB. HULU SUNGAI UTARA', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.09', 'KAB. TABALONG', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.1', 'KAB. TANAH BUMBU', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.11', 'KAB. BALANGAN', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.71', 'KOTA BANJARMASIN', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('63.72', 'KOTA BANJARBARU', NULL, NULL, NULL, '63');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.01', 'KAB. PASER', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.02', 'KAB. KUTAI KARTANEGARA', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.03', 'KAB. BERAU', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.07', 'KAB. KUTAI BARAT', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.08', 'KAB. KUTAI TIMUR', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.09', 'KAB. PENAJAM PASER UTARA', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.11', 'KAB. MAHAKAM ULU', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.71', 'KOTA BALIKPAPAN', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.72', 'KOTA SAMARINDA', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('64.74', 'KOTA BONTANG', NULL, NULL, NULL, '64');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('65.01', 'KAB. BULUNGAN', NULL, NULL, NULL, '65');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('65.02', 'KAB. MALINAU', NULL, NULL, NULL, '65');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('65.03', 'KAB. NUNUKAN', NULL, NULL, NULL, '65');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('65.04', 'KAB. TANA TIDUNG', NULL, NULL, NULL, '65');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('65.71', 'KOTA TARAKAN', NULL, NULL, NULL, '65');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.01', 'KAB. BOLAANG MONGONDOW', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.02', 'KAB. MINAHASA', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.03', 'KAB. KEPULAUAN SANGIHE', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.04', 'KAB. KEPULAUAN TALAUD', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.05', 'KAB. MINAHASA SELATAN', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.06', 'KAB. MINAHASA UTARA', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.07', 'KAB. MINAHASA TENGGARA', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.08', 'KAB. BOLAANG MONGONDOW UTARA', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.09', 'KAB. KEP. SIAU TAGULANDANG BIARO', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.1', 'KAB. BOLAANG MONGONDOW TIMUR', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.11', 'KAB. BOLAANG MONGONDOW SELATAN', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.71', 'KOTA MANADO', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.72', 'KOTA BITUNG', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.73', 'KOTA TOMOHON', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('71.74', 'KOTA KOTAMOBAGU', NULL, NULL, NULL, '71');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.01', 'KAB. BANGGAI', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.02', 'KAB. POSO', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.03', 'KAB. DONGGALA', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.04', 'KAB. TOLI TOLI', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.05', 'KAB. BUOL', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.06', 'KAB. MOROWALI', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.07', 'KAB. BANGGAI KEPULAUAN', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.08', 'KAB. PARIGI MOUTONG', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.09', 'KAB. TOJO UNA UNA', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.1', 'KAB. SIGI', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.11', 'KAB. BANGGAI LAUT', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.12', 'KAB. MOROWALI UTARA', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('72.71', 'KOTA PALU', NULL, NULL, NULL, '72');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.01', 'KAB. KEPULAUAN SELAYAR', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.02', 'KAB. BULUKUMBA', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.03', 'KAB. BANTAENG', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.04', 'KAB. JENEPONTO', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.05', 'KAB. TAKALAR', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.06', 'KAB. GOWA', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.07', 'KAB. SINJAI', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.08', 'KAB. BONE', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.09', 'KAB. MAROS', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.1', 'KAB. PANGKAJENE KEPULAUAN', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.11', 'KAB. BARRU', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.12', 'KAB. SOPPENG', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.13', 'KAB. WAJO', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.14', 'KAB. SIDENRENG RAPPANG', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.15', 'KAB. PINRANG', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.16', 'KAB. ENREKANG', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.17', 'KAB. LUWU', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.18', 'KAB. TANA TORAJA', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.22', 'KAB. LUWU UTARA', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.24', 'KAB. LUWU TIMUR', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.26', 'KAB. TORAJA UTARA', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.71', 'KOTA MAKASSAR', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.72', 'KOTA PARE PARE', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('73.73', 'KOTA PALOPO', NULL, NULL, NULL, '73');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.01', 'KAB. KOLAKA', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.02', 'KAB. KONAWE', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.03', 'KAB. MUNA', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.04', 'KAB. BUTON', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.05', 'KAB. KONAWE SELATAN', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.06', 'KAB. BOMBANA', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.07', 'KAB. WAKATOBI', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.08', 'KAB. KOLAKA UTARA', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.09', 'KAB. KONAWE UTARA', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.1', 'KAB. BUTON UTARA', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.11', 'KAB. KOLAKA TIMUR', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.12', 'KAB. KONAWE KEPULAUAN', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.13', 'KAB. MUNA BARAT', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.14', 'KAB. BUTON TENGAH', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.15', 'KAB. BUTON SELATAN', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.71', 'KOTA KENDARI', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('74.72', 'KOTA BAU BAU', NULL, NULL, NULL, '74');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('75.01', 'KAB. GORONTALO', NULL, NULL, NULL, '75');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('75.02', 'KAB. BOALEMO', NULL, NULL, NULL, '75');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('75.03', 'KAB. BONE BOLANGO', NULL, NULL, NULL, '75');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('75.04', 'KAB. PAHUWATO', NULL, NULL, NULL, '75');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('75.05', 'KAB. GORONTALO UTARA', NULL, NULL, NULL, '75');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('75.71', 'KOTA GORONTALO', NULL, NULL, NULL, '75');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('76.01', 'KAB. PASANGKAYU', NULL, NULL, NULL, '76');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('76.02', 'KAB. MAMUJU', NULL, NULL, NULL, '76');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('76.03', 'KAB. MAMASA', NULL, NULL, NULL, '76');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('76.04', 'KAB. POLEWALI MANDAR', NULL, NULL, NULL, '76');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('76.05', 'KAB. MAJENE', NULL, NULL, NULL, '76');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('76.06', 'KAB. MAMUJU TENGAH', NULL, NULL, NULL, '76');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.01', 'KAB. MALUKU TENGAH', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.02', 'KAB. MALUKU TENGGARA', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.03', 'KAB. KEPULAUAN TANIMBAR', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.04', 'KAB. BURU', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.05', 'KAB. SERAM BAGIAN TIMUR', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.06', 'KAB. SERAM BAGIAN BARAT', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.07', 'KAB. KEPULAUAN ARU', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.08', 'KAB. MALUKU BARAT DAYA', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.09', 'KAB. BURU SELATAN', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.71', 'KOTA AMBON', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('81.72', 'KOTA TUAL', NULL, NULL, NULL, '81');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.01', 'KAB. HALMAHERA BARAT', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.02', 'KAB. HALMAHERA TENGAH', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.03', 'KAB. HALMAHERA UTARA', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.04', 'KAB. HALMAHERA SELATAN', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.05', 'KAB. KEPULAUAN SULA', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.06', 'KAB. HALMAHERA TIMUR', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.07', 'KAB. PULAU MOROTAI', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.08', 'KAB. PULAU TALIABU', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.71', 'KOTA TERNATE', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('82.72', 'KOTA TIDORE KEPULAUAN', NULL, NULL, NULL, '82');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.01', 'KAB. MERAUKE', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.02', 'KAB. JAYAWIJAYA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.03', 'KAB. JAYAPURA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.04', 'KAB. NABIRE', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.05', 'KAB. KEPULAUAN YAPEN', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.06', 'KAB. BIAK NUMFOR', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.07', 'KAB. PUNCAK JAYA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.08', 'KAB. PANIAI', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.09', 'KAB. MIMIKA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.1', 'KAB. SARMI', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.11', 'KAB. KEEROM', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.12', 'KAB. PEGUNUNGAN BINTANG', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.13', 'KAB. YAHUKIMO', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.14', 'KAB. TOLIKARA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.15', 'KAB. WAROPEN', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.16', 'KAB. BOVEN DIGOEL', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.17', 'KAB. MAPPI', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.18', 'KAB. ASMAT', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.19', 'KAB. SUPIORI', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.2', 'KAB. MAMBERAMO RAYA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.21', 'KAB. MAMBERAMO TENGAH', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.22', 'KAB. YALIMO', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.23', 'KAB. LANNY JAYA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.24', 'KAB. NDUGA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.25', 'KAB. PUNCAK', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.26', 'KAB. DOGIYAI', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.27', 'KAB. INTAN JAYA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.28', 'KAB. DEIYAI', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('91.71', 'KOTA JAYAPURA', NULL, NULL, NULL, '91');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.01', 'KAB. SORONG', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.02', 'KAB. MANOKWARI', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.03', 'KAB. FAK FAK', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.04', 'KAB. SORONG SELATAN', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.05', 'KAB. RAJA AMPAT', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.06', 'KAB. TELUK BINTUNI', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.07', 'KAB. TELUK WONDAMA', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.08', 'KAB. KAIMANA', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.09', 'KAB. TAMBRAUW', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.1', 'KAB. MAYBRAT', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.11', 'KAB. MANOKWARI SELATAN', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.12', 'KAB. PEGUNUNGAN ARFAK', NULL, NULL, NULL, '92');
INSERT INTO `kota` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`, `provinsi_id`) VALUES ('92.71', 'KOTA SORONG', NULL, NULL, NULL, '92');
