INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('11', 'ACEH', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('12', 'SUMATERA UTARA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('13', 'SUMATERA BARAT', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('14', 'RIAU', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('15', 'JAMBI', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('16', 'SUMATERA SELATAN', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('17', 'BENGKULU', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('18', 'LAMPUNG', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('19', 'KEPULAUAN BANGKA BELITUNG', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('21', 'KEPULAUAN RIAU', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('31', 'DKI JAKARTA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('32', 'JAWA BARAT', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('33', 'JAWA TENGAH', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('34', 'DAERAH ISTIMEWA YOGYAKARTA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('35', 'JAWA TIMUR', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('36', 'BANTEN', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('51', 'BALI', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('52', 'NUSA TENGGARA BARAT', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('53', 'NUSA TENGGARA TIMUR', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('61', 'KALIMANTAN BARAT', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('62', 'KALIMANTAN TENGAH', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('63', 'KALIMANTAN SELATAN', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('64', 'KALIMANTAN TIMUR', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('65', 'KALIMANTAN UTARA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('71', 'SULAWESI UTARA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('72', 'SULAWESI TENGAH', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('73', 'SULAWESI SELATAN', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('74', 'SULAWESI TENGGARA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('75', 'GORONTALO', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('76', 'SULAWESI BARAT', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('81', 'MALUKU', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('82', 'MALUKU UTARA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('91', 'PAPUA', NULL, NULL, NULL);
INSERT INTO `provinsis` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES ('92', 'PAPUA BARAT', NULL, NULL, NULL);
